name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DESAFIO_M5_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Debug SSH key
        run: |
          ls -al ~/.ssh
          cat ~/.ssh/id_rsa || echo "Clave no disponible"

      - name: Add EC2 to known_hosts
        run: ssh-keyscan -H 54.224.58.127 >> ~/.ssh/known_hosts

      - name: Clone repository on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@54.224.58.127 "
          git clone https://github.com/antoruizx/desafio-1-m5.git /home/ec2-user/app || (cd /home/ec2-user/app && git pull)"

      - name: Install dependencies on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@54.224.58.127 "
          cd /home/ec2-user/app && 
          sudo yum update -y &&
          curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash - &&
          sudo yum install -y nodejs &&
          npm install"

      - name: Start application
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@54.224.58.127 "
          cd /home/ec2-user/app && 
          nohup npm start > app.log 2>&1 &"
